# Site settings
title: russelldub web experiments
email: russelldub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A thing I try.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://russelldub.github.io" # the base hostname & protocol for your site
twitter_username: oddmissive
github_username:  russelldub

# Build settings
markdown: kramdown
